version: '3'

services:
  bot:
    build:
      context: ./
      dockerfile: containers/${DOCKERFILE_PREFIX}Dockerfile
    network_mode: host
    volumes:
      - ${DOCKERFILE_SRC_VOLUME}
    env_file:
      - .env
    command: bash -c 'set -a; source .env; set +a; python main.py'

  mongo:
    image: mongo
    ports:
        - 27017:27017
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  mongo-express:
    image: mongo-express
    ports:
        - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_PASSWORD}

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/var/lib/redis

volumes:
  mongo_data:
  redis_data:
